name: Linting, testing, building
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
      - uses: actions/checkout@v3
      - name: Setup Node.js
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install modules
        run: npm install
      - name: Build prod project
        run: npm run build:prod
      - name: Linting TypeScript
        run: npm run lint:ts
      - name: Unit testing
        run: npm run test:unit